# Generated by Django 5.1.4 on 2024-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TL", "Turkish Lira"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                ],
                max_length=3,
            ),
        ),
    ]
